/**
 * Author:  José Flávio
 * Created: 30/05/2017
 */

CREATE TABLE coleta
(
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    descricao VARCHAR(30) NOT NULL,
    dataColeta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE leitura
(
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    coleta INTEGER NOT NULL,
    localLeitura VARCHAR(30) NOT NULL,
    leitura REAL NOT NULL,
    unidade VARCHAR(30) NOT NULL,
    atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

